# <font color=blue> Array manipulation All-in-one
Array manipulation is the fundamentals of all programming
Often, we spend lots of time figuring the syntax or keyword to accomplish a certain task
Worst, we write inefficient codes to achieve a particular task (eg. sort)

Reference: http://cs231n.github.io/python-numpy-tutorial/#numpy

In [2]:
import numpy as np

In [1]:
#Count occurrences of element in multi-dimensional array
game = np.array([
          ['F','W','E','L','D','H'],
          ['H','D','L','W','F','E'],
          ['E','H','F','L','W','L'],
          ['L','F','D','F','H','W'],
          ['F','F','L','E','H','W']])
unique, counts = np.unique(game, return_counts=True)
print(unique)
print(counts)

print(np.sort(counts))

['D' 'E' 'F' 'H' 'L' 'W']
[3 4 7 5 6 5]
[3 4 5 5 6 7]


In [36]:
# Remove first occurrence of an element matching the value
a = ['a','b','c','d']
a.remove('b')
print(a)

['a', 'c', 'd']


In [3]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [5]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print('Query1:', col_r1, col_r1.shape)
print('Query2:', col_r2, col_r2.shape) 

Query1: [ 2  6 10] (3,)
Query2: [[ 2]
 [ 6]
 [10]] (3, 1)


In [3]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]


In [7]:
# np.arrange(start=0, stop, step=1, dtype=None)

#create an array of sequential number from 0 to before 5 in steps of 1
print(np.arange(5))

#create an array of sequential number from 5 to before 20 in steps of 3
print(np.arange(5,20,3))

#arange works for decimal as well but its better to use linspace instead

[0 1 2 3 4]
[ 5  8 11 14 17]


In [9]:
# Importatnt!!!!!
# This behavior caosts me days of debugging.
# Take note of how values are being passed!
a = [2, [3,4]]
b = a
a[1] = [9,9]
print('a:', a)
print('b:',b)    #value of b also changes!!!!

a: [2, [9, 9]]
b: [2, [9, 9]]


In [13]:
# Another example to take note on how python pa
def f1(list):
    print('Within function pre-process:', list)
    list += [47, 11]
    print('Within function post-process:', list)

abc = [1, 2, 3]
f1(abc)
print('In global after function:', abc)
print('------------------------------------------------')
xyz = [4, 5, 6]
f1(xyz[:])
print('In global after function:', xyz)

Within function pre-process: [1, 2, 3]
Within function post-process: [1, 2, 3, 47, 11]
In global after function: [1, 2, 3, 47, 11]
------------------------------------------------
Within function pre-process: [4, 5, 6]
Within function post-process: [4, 5, 6, 47, 11]
In global after function: [4, 5, 6]
