# <font color=blue> Open CV Tutorial: Paste an image on another image

In [6]:
import os
import cv2

#change the path and image file name to your own when running this script
path = "C:\\Users\\kim_c\\OneDrive - National University of Singapore\\GitHub\\ToS"
# Load the "bigger" image to img1
img1 = cv2.imread(path + '\\boardNorm-001.png')

# Load the smaller image to img2
img2 = cv2.imread(path + '\\stdFire-001.png')

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]

# Now create a mask of logo and create its inverse mask also
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

# Now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)

# Take only region of logo from logo image.
img2_fg = cv2.bitwise_and(img2,img2,mask = mask)

# Put logo in ROI and modify the main image
dst = cv2.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst

cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import os
import cv2

path = "C:\\Users\\kim_c\\OneDrive - National University of Singapore\\GitHub\\ToS"
#img1 = cv2.imread(path + '\\boardNorm-001.png')
img1 = cv2.imread(path + '\\stdFire-001.png')
cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
import os
import cv2

#change the path and image file name to your own when running this script
path = "C:\\Users\\kim_c\\OneDrive - National University of Singapore\\GitHub\\ToS"
# Load the "bigger" image to img1
img1 = cv2.imread(path + '\\boardNorm-001.png')

# Load the smaller image to img2
img2 = cv2.imread(path + '\\stdFire-001.png')

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
#roi = img1[0:rows, 0:cols ]

# Now create a mask of logo and create its inverse mask also
#img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
#ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
#mask_inv = cv2.bitwise_not(mask)

# Now black-out the area of logo in ROI
#img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)

# Take only region of logo from logo image.
#img2_fg = cv2.bitwise_and(img2,img2,mask = mask)

# Put logo in ROI and modify the main image
#dst = cv2.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = img2

cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
import numpy as np

runeIndex = {'F' : 1,
             'W' : 2,
             'E' : 3,
             'L' : 4,
             'D' : 5,
             'H' : 6}

#foodOnHand['roe'] += 10
#print("Rice: ", foodOnHand['rice'], "Roe: ", foodOnHand['roe'])
rIndex = ['F','W','E','L','D','H']

game = np.array([
        ['F','W','E','L','D','H'],
        ['H','D','L','W','F','E'],
        ['E','H','F','L','W','L'],
        ['L','F','D','F','H','W'],
        ['F','F','L','E','H','W']])

print(rIndex.index('F'))

0


In [7]:
from PIL import Image, ImageGrab, ImageOps
import numpy as np

im = ImageGrab.grab((765, 493, 765+68, 493+68))
print(im)
cImage = np.array(im)
print(cImage)

<PIL.Image.Image image mode=RGB size=68x68 at 0x1D24B7509B0>
[[[60 47 25]
  [61 45 25]
  [68 55 32]
  ...
  [47 31  8]
  [55 35  9]
  [56 35 10]]

 [[44 32 14]
  [63 48 33]
  [57 43 27]
  ...
  [37 24  8]
  [44 27 10]
  [51 30 11]]

 [[42 33 17]
  [56 45 31]
  [30 20  5]
  ...
  [41 24  8]
  [48 26 10]
  [55 29 14]]

 ...

 [[32 17 10]
  [30 17  7]
  [31 19  7]
  ...
  [41 24 16]
  [41 26 12]
  [47 34 14]]

 [[32 20 10]
  [30 18  7]
  [31 19  7]
  ...
  [41 24 16]
  [41 26 12]
  [47 34 14]]

 [[32 20 10]
  [30 18  7]
  [31 19  7]
  ...
  [41 24 12]
  [43 25 10]
  [51 32 14]]]


In [4]:
for eachElem in cImage:
    print(eachElem)

TypeError: iteration over a 0-d array